// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJA2h827DPFr7AakesPYodgKiN7Z8rmg',
    appId: '1:222478628756:web:ccda23ac9bbcf4b2d78181',
    messagingSenderId: '222478628756',
    projectId: 'viflow-app-be664',
    authDomain: 'viflow-app-be664.firebaseapp.com',
    storageBucket: 'viflow-app-be664.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlp70QqsiaiofTQPWVtGIqXWZAXncnvk',
    appId: '1:222478628756:android:ce479145f47a9a17d78181',
    messagingSenderId: '222478628756',
    projectId: 'viflow-app-be664',
    storageBucket: 'viflow-app-be664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh50uQFgoMWD9sMDOqOzfpH--vQA6Ggnc',
    appId: '1:222478628756:ios:6033f1a35efdf377d78181',
    messagingSenderId: '222478628756',
    projectId: 'viflow-app-be664',
    storageBucket: 'viflow-app-be664.firebasestorage.app',
    iosClientId: '222478628756-625qgva61n464b5trb8uke5re1fbfuqs.apps.googleusercontent.com',
    iosBundleId: 'com.viflow.app.viflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh50uQFgoMWD9sMDOqOzfpH--vQA6Ggnc',
    appId: '1:222478628756:ios:41b3b8b17fdf7cc7d78181',
    messagingSenderId: '222478628756',
    projectId: 'viflow-app-be664',
    storageBucket: 'viflow-app-be664.firebasestorage.app',
    iosClientId: '222478628756-pq4uuf5g3rdr8j4f3t0mus866t0vlqhk.apps.googleusercontent.com',
    iosBundleId: 'com.viflow.app.viflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVJA2h827DPFr7AakesPYodgKiN7Z8rmg',
    appId: '1:222478628756:web:5a78d4dc48d4b8ffd78181',
    messagingSenderId: '222478628756',
    projectId: 'viflow-app-be664',
    authDomain: 'viflow-app-be664.firebaseapp.com',
    storageBucket: 'viflow-app-be664.firebasestorage.app',
  );

}