// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTraX0RJMN5wcwnERsBfBH2MWHODr3noc',
    appId: '1:523503900616:web:6287a2a4791b123ca7d2fd',
    messagingSenderId: '523503900616',
    projectId: 'viflow-22e4f',
    authDomain: 'viflow-22e4f.firebaseapp.com',
    storageBucket: 'viflow-22e4f.firebasestorage.app',
    measurementId: 'G-Y2ETCQJFKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrxyOmYzf2HgYd-JQq0k0P_WBtr6RYoX8',
    appId: '1:523503900616:android:f5dbc76d473212d9a7d2fd',
    messagingSenderId: '523503900616',
    projectId: 'viflow-22e4f',
    storageBucket: 'viflow-22e4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfcW_FMoSpwZAmSl--wZiSpk3lTO2kfso',
    appId: '1:523503900616:ios:bee6809c6de81b0ea7d2fd',
    messagingSenderId: '523503900616',
    projectId: 'viflow-22e4f',
    storageBucket: 'viflow-22e4f.firebasestorage.app',
    iosBundleId: 'com.viflow.app.viflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfcW_FMoSpwZAmSl--wZiSpk3lTO2kfso',
    appId: '1:523503900616:ios:bee6809c6de81b0ea7d2fd',
    messagingSenderId: '523503900616',
    projectId: 'viflow-22e4f',
    storageBucket: 'viflow-22e4f.firebasestorage.app',
    iosBundleId: 'com.viflow.app.viflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTraX0RJMN5wcwnERsBfBH2MWHODr3noc',
    appId: '1:523503900616:web:c4a65a1844859cf2a7d2fd',
    messagingSenderId: '523503900616',
    projectId: 'viflow-22e4f',
    authDomain: 'viflow-22e4f.firebaseapp.com',
    storageBucket: 'viflow-22e4f.firebasestorage.app',
    measurementId: 'G-HXR9Y7YXV9',
  );
}
